import {
    D_ICE_CODE,
    DOWN_ICE_CODE,
    GD_ICE_CODE,
    GOV_ICE_CODE,
    ICE_CODE,
    ICE_ISSUER,
    UP_ICE_CODE,
} from './assets-env';

export const DEFAULT_ICE_ASSETS = [
    `${ICE_CODE}:${ICE_ISSUER}`,
    `${GOV_ICE_CODE}:${ICE_ISSUER}`,
    `${UP_ICE_CODE}:${ICE_ISSUER}`,
    `${DOWN_ICE_CODE}:${ICE_ISSUER}`,
];

export const DELEGATED_ICE_ASSETS = [`${D_ICE_CODE}:${ICE_ISSUER}`, `${GD_ICE_CODE}:${ICE_ISSUER}`];

export const ICE_TO_DELEGATE = [`${UP_ICE_CODE}:${ICE_ISSUER}`, `${GOV_ICE_CODE}:${ICE_ISSUER}`];

export const ICE_DELEGATION_MAP = new Map([
    [`${UP_ICE_CODE}:${ICE_ISSUER}`, `${D_ICE_CODE}:${ICE_ISSUER}`],
    [`${GOV_ICE_CODE}:${ICE_ISSUER}`, `${GD_ICE_CODE}:${ICE_ISSUER}`],
]);

export const ALL_ICE_ASSETS = [...DEFAULT_ICE_ASSETS, ...DELEGATED_ICE_ASSETS];

export const PYUSD_CODE = 'PYUSD';
export const PYUSD_ISSUER = 'GDQE7IXJ4HUHV6RQHIUPRJSEZE4DRS5WY577O2FY6YQ5LVWZ7JZTU2V5';
